
version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    go-minor:
      update-types:
        - minor
        - patch

- package-ecosystem: "npm"
  directory: "/docs"
  schedule:
    interval: "weekly"
  groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    actions-minor:
      update-types:
        - minor
        - patch
