version: 1

project_name: kitops

before:
  hooks:
    - go mod tidy

builds:
  - id: "kit-linux"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    binary: kit
    ldflags:
      - -s -w -X kitops/pkg/cmd/version.Version={{.Version}} -X kitops/pkg/cmd/version.GitCommit={{.Commit}} -X kitops/pkg/cmd/version.BuildTime={{.CommitDate}}

archives:
  - id: kit-archive
    format: tar.gz
    builds:
      - kit-linux
    name_template: >-
      {{ .ProjectName }}-
      {{- tolower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    rlcp: true
    files:
      - LICENSE
      - README.md

git:
  ignore_tags:
    - "next"

snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"