
version: 1

project_name: kitops

before:
  hooks:
    - go mod tidy

builds:
  - id: "kit"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    binary: kit
    ldflags:
      - -s -w -X kitops/pkg/cmd/version.Version={{.Version}} -X kitops/pkg/cmd/version.GitCommit={{.Commit}} -X kitops/pkg/cmd/version.BuildTime={{.CommitDate}}

  - id: "kit-macos"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    binary: kit
    ldflags:
      - -s -w -X kitops/pkg/cmd/version.Version={{.Version}} -X kitops/pkg/cmd/version.GitCommit={{.Commit}} -X kitops/pkg/cmd/version.BuildTime={{.CommitDate}}
    hooks:
      post: |-
        sh -c '
        cat <<EOF > /tmp/kit-gon.hcl
        source = ["./dist/kit-macos_darwin_{{ .Arch }}{{- if .Amd64 }}_{{ .Amd64 }}{{ end }}/kit"]
        bundle_id = "com.jozu-ai.kitops"
        apple_id {
          provider = "PMHBCVV9C2"
        }
        sign {
          application_identity = "Developer ID Application: AKARA TECHNOLOGIES, INC. (PMHBCVV9C2)"
        }
        zip {
          output_path = "./dist/kitops-darwin-{{ .Arch }}.zip"
        }
        EOF
        gon /tmp/kit-gon.hcl
        '

archives:
  - format: tar.gz
    builds:
      - kit
    name_template: >-
      {{ .ProjectName }}-
      {{- tolower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

git:
  ignore_tags:
    - "next"

release:
  github:
    owner: jozu-ai
    name: kitops
  header: |
    ## Kitops Release {{.Version}} ({{ .Date }})

  footer: |
    Thanks for supporting Kitops.

  name_template: "{{.ProjectName}}-{{.Version}}"
  skip_upload: false
