version: 2

project_name: kitops

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: "kit-linux"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    binary: kit
    ldflags:
      - -s -w -X kitops/pkg/lib/constants.Version={{.Version}} -X kitops/pkg/lib/constants.GitCommit={{.Commit}} -X kitops/pkg/lib/constants.BuildTime={{.CommitDate}}
  - id: "kit-linux-embedded"
    flags: 
      - --tags=embed_harness
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    binary: kit
    ldflags:
      - -s -w -X kitops/pkg/lib/constants.Version={{.Version}} -X kitops/pkg/lib/constants.GitCommit={{.Commit}} -X kitops/pkg/lib/constants.BuildTime={{.CommitDate}}

archives:
  - id: kit-archive
    format: tar.gz
    builds:
      - kit-linux
    name_template: >-
      {{ .ProjectName }}-
      {{- tolower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
  - id: kit-archive-offile
    format: tar.gz
    builds:
      - kit-linux-embedded
    name_template: >-
      {{ .ProjectName }}-offline-
      {{- tolower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md

git:
  ignore_tags:
    - "next"

snapshot:
  name_template: "{{ .Version }}"