name: Build the dev mode UI

on:
  # Runs on pushes targeting the `main` branch, and only for the `frontend/dev-mode/**` path.
  pull_request:
    paths:
      - 'frontend/dev-mode/**'

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PNPM_CACHE_STORE_PATH: ""

jobs:
  build-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      ## install build dependencies for frontend generation
      - name: Install Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: './frontend/dev-mode/.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 8
          package_json_file: frontend/dev-mode/package.json
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "PNPM_CACHE_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        name: Setup pnpm cache
        with:
          path: ${{ env.PNPM_CACHE_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          cd ./frontend/dev-mode
          pnpm install

      - name: Run the build
        run: |
          cd ./frontend/dev-mode
          pnpm build
