name: Next CLI container build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: docs/

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  INIT_IMAGE_NAME: ${{ github.repository }}-init
  NEXT_TAG: next

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392    # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2  # v3.10.0

      - name: Login to ghcr.io
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567         # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build and push base Kit container
        id: build-kit-container
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4    # v6.15.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: build/dockerfiles/Dockerfile
          build-args: |
            KIT_VERSION=${{ github.ref_name }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.NEXT_TAG }}
          annotations: |
            index:org.opencontainers.image.description=Kit CLI container built from source
            index:org.opencontainers.image.source=https://github.com/jozu-ai/kitops
            index:org.opencontainers.image.licenses=Apache-2.0

      - name: Build and push Kit init container
        id: build-kit-init-container
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4    # v6.15.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: build/dockerfiles/init
          file: build/dockerfiles/init/Dockerfile
          build-args: |
            KIT_BASE_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-kit-container.outputs.digest }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.INIT_IMAGE_NAME }}:${{ env.NEXT_TAG }}
          annotations: |
            index:org.opencontainers.image.description=Kit CLI init container
            index:org.opencontainers.image.source=https://github.com/jozu-ai/kitops
            index:org.opencontainers.image.licenses=Apache-2.0

      # - name: Generate artifact attestation for base container
      #   uses: actions/attest-build-provenance@6149ea5740be74af77f260b9db67e633f6b0a9a1   # v1.4.2
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     subject-digest: ${{ steps.build-kit-container.outputs.digest }}
      #     push-to-registry: true

      # - name: Generate artifact attestation for base container
      #   uses: actions/attest-build-provenance@6149ea5740be74af77f260b9db67e633f6b0a9a1   # v1.4.2
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.INIT_IMAGE_NAME }}
      #     subject-digest: ${{ steps.build-kit-init-container.outputs.digest }}
      #     push-to-registry: true
